# Generated by Django 5.1.3 on 2024-11-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme_value',
        ),
    ]
